package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.ApiCount;
import com.zhiyong.gateway.dal.domain.ApiCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int countByExample(ApiCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int insert(ApiCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int insertSelective(ApiCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    List<ApiCount> selectByExample(ApiCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    ApiCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApiCount record, @Param("example") ApiCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApiCount record, @Param("example") ApiCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_count
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiCount record);
}