package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.ApiCfg;
import com.zhiyong.gateway.dal.domain.ApiCfgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int countByExample(ApiCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int insert(ApiCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int insertSelective(ApiCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    List<ApiCfg> selectByExample(ApiCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    ApiCfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApiCfg record, @Param("example") ApiCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApiCfg record, @Param("example") ApiCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiCfg record);
}