package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.ApiGroupCfg;
import com.zhiyong.gateway.dal.domain.ApiGroupCfgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiGroupCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int countByExample(ApiGroupCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int insert(ApiGroupCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int insertSelective(ApiGroupCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    List<ApiGroupCfg> selectByExample(ApiGroupCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    ApiGroupCfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApiGroupCfg record, @Param("example") ApiGroupCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApiGroupCfg record, @Param("example") ApiGroupCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiGroupCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiGroupCfg record);
}