package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.ApiParamCfg;
import com.zhiyong.gateway.dal.domain.ApiParamCfgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiParamCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int countByExample(ApiParamCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int insert(ApiParamCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int insertSelective(ApiParamCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    List<ApiParamCfg> selectByExample(ApiParamCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    ApiParamCfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApiParamCfg record, @Param("example") ApiParamCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApiParamCfg record, @Param("example") ApiParamCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiParamCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiParamCfg record);
}