package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.ApiResultCfg;
import com.zhiyong.gateway.dal.domain.ApiResultCfgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiResultCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int countByExample(ApiResultCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int insert(ApiResultCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int insertSelective(ApiResultCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    List<ApiResultCfg> selectByExample(ApiResultCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    ApiResultCfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApiResultCfg record, @Param("example") ApiResultCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApiResultCfg record, @Param("example") ApiResultCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiResultCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiResultCfg record);
}