package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.PojoType;
import com.zhiyong.gateway.dal.domain.PojoTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PojoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int countByExample(PojoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int insert(PojoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int insertSelective(PojoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    List<PojoType> selectByExample(PojoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    PojoType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PojoType record, @Param("example") PojoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PojoType record, @Param("example") PojoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PojoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PojoType record);
}