package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.PojoTypeJson;
import com.zhiyong.gateway.dal.domain.PojoTypeJsonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PojoTypeJsonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int countByExample(PojoTypeJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int insert(PojoTypeJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int insertSelective(PojoTypeJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    List<PojoTypeJson> selectByExample(PojoTypeJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    PojoTypeJson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PojoTypeJson record, @Param("example") PojoTypeJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PojoTypeJson record, @Param("example") PojoTypeJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PojoTypeJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_type_json
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PojoTypeJson record);
}