package com.zhiyong.gateway.dal.dao;

import com.zhiyong.gateway.dal.domain.PojoStruct;
import com.zhiyong.gateway.dal.domain.PojoStructExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PojoStructMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int countByExample(PojoStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int insert(PojoStruct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int insertSelective(PojoStruct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    List<PojoStruct> selectByExample(PojoStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    PojoStruct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PojoStruct record, @Param("example") PojoStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PojoStruct record, @Param("example") PojoStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PojoStruct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pojo_struct
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PojoStruct record);
}