package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class ApiCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.api_name
     *
     * @mbggenerated
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.api_version
     *
     * @mbggenerated
     */
    private String apiVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.count_date
     *
     * @mbggenerated
     */
    private String countDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.total_count
     *
     * @mbggenerated
     */
    private Integer totalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.succ_count
     *
     * @mbggenerated
     */
    private Integer succCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.total_spends
     *
     * @mbggenerated
     */
    private Integer totalSpends;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_count.max_spends
     *
     * @mbggenerated
     */
    private Integer maxSpends;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.id
     *
     * @return the value of api_count.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.id
     *
     * @param id the value for api_count.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.create_time
     *
     * @return the value of api_count.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.create_time
     *
     * @param createTime the value for api_count.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.update_time
     *
     * @return the value of api_count.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.update_time
     *
     * @param updateTime the value for api_count.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.api_name
     *
     * @return the value of api_count.api_name
     *
     * @mbggenerated
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.api_name
     *
     * @param apiName the value for api_count.api_name
     *
     * @mbggenerated
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.api_version
     *
     * @return the value of api_count.api_version
     *
     * @mbggenerated
     */
    public String getApiVersion() {
        return apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.api_version
     *
     * @param apiVersion the value for api_count.api_version
     *
     * @mbggenerated
     */
    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion == null ? null : apiVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.count_date
     *
     * @return the value of api_count.count_date
     *
     * @mbggenerated
     */
    public String getCountDate() {
        return countDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.count_date
     *
     * @param countDate the value for api_count.count_date
     *
     * @mbggenerated
     */
    public void setCountDate(String countDate) {
        this.countDate = countDate == null ? null : countDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.total_count
     *
     * @return the value of api_count.total_count
     *
     * @mbggenerated
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.total_count
     *
     * @param totalCount the value for api_count.total_count
     *
     * @mbggenerated
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.succ_count
     *
     * @return the value of api_count.succ_count
     *
     * @mbggenerated
     */
    public Integer getSuccCount() {
        return succCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.succ_count
     *
     * @param succCount the value for api_count.succ_count
     *
     * @mbggenerated
     */
    public void setSuccCount(Integer succCount) {
        this.succCount = succCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.total_spends
     *
     * @return the value of api_count.total_spends
     *
     * @mbggenerated
     */
    public Integer getTotalSpends() {
        return totalSpends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.total_spends
     *
     * @param totalSpends the value for api_count.total_spends
     *
     * @mbggenerated
     */
    public void setTotalSpends(Integer totalSpends) {
        this.totalSpends = totalSpends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_count.max_spends
     *
     * @return the value of api_count.max_spends
     *
     * @mbggenerated
     */
    public Integer getMaxSpends() {
        return maxSpends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_count.max_spends
     *
     * @param maxSpends the value for api_count.max_spends
     *
     * @mbggenerated
     */
    public void setMaxSpends(Integer maxSpends) {
        this.maxSpends = maxSpends;
    }
}