package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class ApiCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_name
     *
     * @mbggenerated
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_desc
     *
     * @mbggenerated
     */
    private String apiDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_group
     *
     * @mbggenerated
     */
    private Integer apiGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_version
     *
     * @mbggenerated
     */
    private String apiVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.rpc_interface
     *
     * @mbggenerated
     */
    private String rpcInterface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.rpc_method
     *
     * @mbggenerated
     */
    private String rpcMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.rpc_version
     *
     * @mbggenerated
     */
    private String rpcVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.timeout
     *
     * @mbggenerated
     */
    private Integer timeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.format
     *
     * @mbggenerated
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.sign_type
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.call_limit
     *
     * @mbggenerated
     */
    private Integer callLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.need_login
     *
     * @mbggenerated
     */
    private Integer needLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.need_auth
     *
     * @mbggenerated
     */
    private Integer needAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.http_method
     *
     * @mbggenerated
     */
    private String httpMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_type
     *
     * @mbggenerated
     */
    private Integer apiType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.id
     *
     * @return the value of api.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.id
     *
     * @param id the value for api.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.create_time
     *
     * @return the value of api.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.create_time
     *
     * @param createTime the value for api.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.update_time
     *
     * @return the value of api.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.update_time
     *
     * @param updateTime the value for api.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.deleted
     *
     * @return the value of api.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.deleted
     *
     * @param deleted the value for api.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.state
     *
     * @return the value of api.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.state
     *
     * @param state the value for api.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.creator
     *
     * @return the value of api.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.creator
     *
     * @param creator the value for api.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.updater
     *
     * @return the value of api.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.updater
     *
     * @param updater the value for api.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_name
     *
     * @return the value of api.api_name
     *
     * @mbggenerated
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_name
     *
     * @param apiName the value for api.api_name
     *
     * @mbggenerated
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_desc
     *
     * @return the value of api.api_desc
     *
     * @mbggenerated
     */
    public String getApiDesc() {
        return apiDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_desc
     *
     * @param apiDesc the value for api.api_desc
     *
     * @mbggenerated
     */
    public void setApiDesc(String apiDesc) {
        this.apiDesc = apiDesc == null ? null : apiDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_group
     *
     * @return the value of api.api_group
     *
     * @mbggenerated
     */
    public Integer getApiGroup() {
        return apiGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_group
     *
     * @param apiGroup the value for api.api_group
     *
     * @mbggenerated
     */
    public void setApiGroup(Integer apiGroup) {
        this.apiGroup = apiGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_version
     *
     * @return the value of api.api_version
     *
     * @mbggenerated
     */
    public String getApiVersion() {
        return apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_version
     *
     * @param apiVersion the value for api.api_version
     *
     * @mbggenerated
     */
    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion == null ? null : apiVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.rpc_interface
     *
     * @return the value of api.rpc_interface
     *
     * @mbggenerated
     */
    public String getRpcInterface() {
        return rpcInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.rpc_interface
     *
     * @param rpcInterface the value for api.rpc_interface
     *
     * @mbggenerated
     */
    public void setRpcInterface(String rpcInterface) {
        this.rpcInterface = rpcInterface == null ? null : rpcInterface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.rpc_method
     *
     * @return the value of api.rpc_method
     *
     * @mbggenerated
     */
    public String getRpcMethod() {
        return rpcMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.rpc_method
     *
     * @param rpcMethod the value for api.rpc_method
     *
     * @mbggenerated
     */
    public void setRpcMethod(String rpcMethod) {
        this.rpcMethod = rpcMethod == null ? null : rpcMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.rpc_version
     *
     * @return the value of api.rpc_version
     *
     * @mbggenerated
     */
    public String getRpcVersion() {
        return rpcVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.rpc_version
     *
     * @param rpcVersion the value for api.rpc_version
     *
     * @mbggenerated
     */
    public void setRpcVersion(String rpcVersion) {
        this.rpcVersion = rpcVersion == null ? null : rpcVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.timeout
     *
     * @return the value of api.timeout
     *
     * @mbggenerated
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.timeout
     *
     * @param timeout the value for api.timeout
     *
     * @mbggenerated
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.format
     *
     * @return the value of api.format
     *
     * @mbggenerated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.format
     *
     * @param format the value for api.format
     *
     * @mbggenerated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.sign_type
     *
     * @return the value of api.sign_type
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.sign_type
     *
     * @param signType the value for api.sign_type
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.call_limit
     *
     * @return the value of api.call_limit
     *
     * @mbggenerated
     */
    public Integer getCallLimit() {
        return callLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.call_limit
     *
     * @param callLimit the value for api.call_limit
     *
     * @mbggenerated
     */
    public void setCallLimit(Integer callLimit) {
        this.callLimit = callLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.need_login
     *
     * @return the value of api.need_login
     *
     * @mbggenerated
     */
    public Integer getNeedLogin() {
        return needLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.need_login
     *
     * @param needLogin the value for api.need_login
     *
     * @mbggenerated
     */
    public void setNeedLogin(Integer needLogin) {
        this.needLogin = needLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.need_auth
     *
     * @return the value of api.need_auth
     *
     * @mbggenerated
     */
    public Integer getNeedAuth() {
        return needAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.need_auth
     *
     * @param needAuth the value for api.need_auth
     *
     * @mbggenerated
     */
    public void setNeedAuth(Integer needAuth) {
        this.needAuth = needAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.http_method
     *
     * @return the value of api.http_method
     *
     * @mbggenerated
     */
    public String getHttpMethod() {
        return httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.http_method
     *
     * @param httpMethod the value for api.http_method
     *
     * @mbggenerated
     */
    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod == null ? null : httpMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_type
     *
     * @return the value of api.api_type
     *
     * @mbggenerated
     */
    public Integer getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_type
     *
     * @param apiType the value for api.api_type
     *
     * @mbggenerated
     */
    public void setApiType(Integer apiType) {
        this.apiType = apiType;
    }
}