package com.zhiyong.gateway.dal.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApiCfgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public ApiCfgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andApiNameIsNull() {
            addCriterion("api_name is null");
            return (Criteria) this;
        }

        public Criteria andApiNameIsNotNull() {
            addCriterion("api_name is not null");
            return (Criteria) this;
        }

        public Criteria andApiNameEqualTo(String value) {
            addCriterion("api_name =", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotEqualTo(String value) {
            addCriterion("api_name <>", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameGreaterThan(String value) {
            addCriterion("api_name >", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameGreaterThanOrEqualTo(String value) {
            addCriterion("api_name >=", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLessThan(String value) {
            addCriterion("api_name <", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLessThanOrEqualTo(String value) {
            addCriterion("api_name <=", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLike(String value) {
            addCriterion("api_name like", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotLike(String value) {
            addCriterion("api_name not like", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameIn(List<String> values) {
            addCriterion("api_name in", values, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotIn(List<String> values) {
            addCriterion("api_name not in", values, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameBetween(String value1, String value2) {
            addCriterion("api_name between", value1, value2, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotBetween(String value1, String value2) {
            addCriterion("api_name not between", value1, value2, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiDescIsNull() {
            addCriterion("api_desc is null");
            return (Criteria) this;
        }

        public Criteria andApiDescIsNotNull() {
            addCriterion("api_desc is not null");
            return (Criteria) this;
        }

        public Criteria andApiDescEqualTo(String value) {
            addCriterion("api_desc =", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescNotEqualTo(String value) {
            addCriterion("api_desc <>", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescGreaterThan(String value) {
            addCriterion("api_desc >", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescGreaterThanOrEqualTo(String value) {
            addCriterion("api_desc >=", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescLessThan(String value) {
            addCriterion("api_desc <", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescLessThanOrEqualTo(String value) {
            addCriterion("api_desc <=", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescLike(String value) {
            addCriterion("api_desc like", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescNotLike(String value) {
            addCriterion("api_desc not like", value, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescIn(List<String> values) {
            addCriterion("api_desc in", values, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescNotIn(List<String> values) {
            addCriterion("api_desc not in", values, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescBetween(String value1, String value2) {
            addCriterion("api_desc between", value1, value2, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiDescNotBetween(String value1, String value2) {
            addCriterion("api_desc not between", value1, value2, "apiDesc");
            return (Criteria) this;
        }

        public Criteria andApiGroupIsNull() {
            addCriterion("api_group is null");
            return (Criteria) this;
        }

        public Criteria andApiGroupIsNotNull() {
            addCriterion("api_group is not null");
            return (Criteria) this;
        }

        public Criteria andApiGroupEqualTo(Integer value) {
            addCriterion("api_group =", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupNotEqualTo(Integer value) {
            addCriterion("api_group <>", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupGreaterThan(Integer value) {
            addCriterion("api_group >", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("api_group >=", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupLessThan(Integer value) {
            addCriterion("api_group <", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupLessThanOrEqualTo(Integer value) {
            addCriterion("api_group <=", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupIn(List<Integer> values) {
            addCriterion("api_group in", values, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupNotIn(List<Integer> values) {
            addCriterion("api_group not in", values, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupBetween(Integer value1, Integer value2) {
            addCriterion("api_group between", value1, value2, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("api_group not between", value1, value2, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiVersionIsNull() {
            addCriterion("api_version is null");
            return (Criteria) this;
        }

        public Criteria andApiVersionIsNotNull() {
            addCriterion("api_version is not null");
            return (Criteria) this;
        }

        public Criteria andApiVersionEqualTo(String value) {
            addCriterion("api_version =", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotEqualTo(String value) {
            addCriterion("api_version <>", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionGreaterThan(String value) {
            addCriterion("api_version >", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionGreaterThanOrEqualTo(String value) {
            addCriterion("api_version >=", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionLessThan(String value) {
            addCriterion("api_version <", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionLessThanOrEqualTo(String value) {
            addCriterion("api_version <=", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionLike(String value) {
            addCriterion("api_version like", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotLike(String value) {
            addCriterion("api_version not like", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionIn(List<String> values) {
            addCriterion("api_version in", values, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotIn(List<String> values) {
            addCriterion("api_version not in", values, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionBetween(String value1, String value2) {
            addCriterion("api_version between", value1, value2, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotBetween(String value1, String value2) {
            addCriterion("api_version not between", value1, value2, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceIsNull() {
            addCriterion("rpc_interface is null");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceIsNotNull() {
            addCriterion("rpc_interface is not null");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceEqualTo(String value) {
            addCriterion("rpc_interface =", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceNotEqualTo(String value) {
            addCriterion("rpc_interface <>", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceGreaterThan(String value) {
            addCriterion("rpc_interface >", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceGreaterThanOrEqualTo(String value) {
            addCriterion("rpc_interface >=", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceLessThan(String value) {
            addCriterion("rpc_interface <", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceLessThanOrEqualTo(String value) {
            addCriterion("rpc_interface <=", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceLike(String value) {
            addCriterion("rpc_interface like", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceNotLike(String value) {
            addCriterion("rpc_interface not like", value, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceIn(List<String> values) {
            addCriterion("rpc_interface in", values, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceNotIn(List<String> values) {
            addCriterion("rpc_interface not in", values, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceBetween(String value1, String value2) {
            addCriterion("rpc_interface between", value1, value2, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcInterfaceNotBetween(String value1, String value2) {
            addCriterion("rpc_interface not between", value1, value2, "rpcInterface");
            return (Criteria) this;
        }

        public Criteria andRpcMethodIsNull() {
            addCriterion("rpc_method is null");
            return (Criteria) this;
        }

        public Criteria andRpcMethodIsNotNull() {
            addCriterion("rpc_method is not null");
            return (Criteria) this;
        }

        public Criteria andRpcMethodEqualTo(String value) {
            addCriterion("rpc_method =", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodNotEqualTo(String value) {
            addCriterion("rpc_method <>", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodGreaterThan(String value) {
            addCriterion("rpc_method >", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodGreaterThanOrEqualTo(String value) {
            addCriterion("rpc_method >=", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodLessThan(String value) {
            addCriterion("rpc_method <", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodLessThanOrEqualTo(String value) {
            addCriterion("rpc_method <=", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodLike(String value) {
            addCriterion("rpc_method like", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodNotLike(String value) {
            addCriterion("rpc_method not like", value, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodIn(List<String> values) {
            addCriterion("rpc_method in", values, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodNotIn(List<String> values) {
            addCriterion("rpc_method not in", values, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodBetween(String value1, String value2) {
            addCriterion("rpc_method between", value1, value2, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcMethodNotBetween(String value1, String value2) {
            addCriterion("rpc_method not between", value1, value2, "rpcMethod");
            return (Criteria) this;
        }

        public Criteria andRpcVersionIsNull() {
            addCriterion("rpc_version is null");
            return (Criteria) this;
        }

        public Criteria andRpcVersionIsNotNull() {
            addCriterion("rpc_version is not null");
            return (Criteria) this;
        }

        public Criteria andRpcVersionEqualTo(String value) {
            addCriterion("rpc_version =", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionNotEqualTo(String value) {
            addCriterion("rpc_version <>", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionGreaterThan(String value) {
            addCriterion("rpc_version >", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionGreaterThanOrEqualTo(String value) {
            addCriterion("rpc_version >=", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionLessThan(String value) {
            addCriterion("rpc_version <", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionLessThanOrEqualTo(String value) {
            addCriterion("rpc_version <=", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionLike(String value) {
            addCriterion("rpc_version like", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionNotLike(String value) {
            addCriterion("rpc_version not like", value, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionIn(List<String> values) {
            addCriterion("rpc_version in", values, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionNotIn(List<String> values) {
            addCriterion("rpc_version not in", values, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionBetween(String value1, String value2) {
            addCriterion("rpc_version between", value1, value2, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andRpcVersionNotBetween(String value1, String value2) {
            addCriterion("rpc_version not between", value1, value2, "rpcVersion");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNull() {
            addCriterion("timeout is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNotNull() {
            addCriterion("timeout is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutEqualTo(Integer value) {
            addCriterion("timeout =", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotEqualTo(Integer value) {
            addCriterion("timeout <>", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThan(Integer value) {
            addCriterion("timeout >", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("timeout >=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThan(Integer value) {
            addCriterion("timeout <", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("timeout <=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutIn(List<Integer> values) {
            addCriterion("timeout in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotIn(List<Integer> values) {
            addCriterion("timeout not in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("timeout between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("timeout not between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andFormatIsNull() {
            addCriterion("format is null");
            return (Criteria) this;
        }

        public Criteria andFormatIsNotNull() {
            addCriterion("format is not null");
            return (Criteria) this;
        }

        public Criteria andFormatEqualTo(String value) {
            addCriterion("format =", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotEqualTo(String value) {
            addCriterion("format <>", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThan(String value) {
            addCriterion("format >", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThanOrEqualTo(String value) {
            addCriterion("format >=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThan(String value) {
            addCriterion("format <", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThanOrEqualTo(String value) {
            addCriterion("format <=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLike(String value) {
            addCriterion("format like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotLike(String value) {
            addCriterion("format not like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatIn(List<String> values) {
            addCriterion("format in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotIn(List<String> values) {
            addCriterion("format not in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatBetween(String value1, String value2) {
            addCriterion("format between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotBetween(String value1, String value2) {
            addCriterion("format not between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNull() {
            addCriterion("sign_type is null");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNotNull() {
            addCriterion("sign_type is not null");
            return (Criteria) this;
        }

        public Criteria andSignTypeEqualTo(String value) {
            addCriterion("sign_type =", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotEqualTo(String value) {
            addCriterion("sign_type <>", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThan(String value) {
            addCriterion("sign_type >", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sign_type >=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThan(String value) {
            addCriterion("sign_type <", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThanOrEqualTo(String value) {
            addCriterion("sign_type <=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLike(String value) {
            addCriterion("sign_type like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotLike(String value) {
            addCriterion("sign_type not like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeIn(List<String> values) {
            addCriterion("sign_type in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotIn(List<String> values) {
            addCriterion("sign_type not in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeBetween(String value1, String value2) {
            addCriterion("sign_type between", value1, value2, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotBetween(String value1, String value2) {
            addCriterion("sign_type not between", value1, value2, "signType");
            return (Criteria) this;
        }

        public Criteria andCallLimitIsNull() {
            addCriterion("call_limit is null");
            return (Criteria) this;
        }

        public Criteria andCallLimitIsNotNull() {
            addCriterion("call_limit is not null");
            return (Criteria) this;
        }

        public Criteria andCallLimitEqualTo(Integer value) {
            addCriterion("call_limit =", value, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitNotEqualTo(Integer value) {
            addCriterion("call_limit <>", value, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitGreaterThan(Integer value) {
            addCriterion("call_limit >", value, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("call_limit >=", value, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitLessThan(Integer value) {
            addCriterion("call_limit <", value, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitLessThanOrEqualTo(Integer value) {
            addCriterion("call_limit <=", value, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitIn(List<Integer> values) {
            addCriterion("call_limit in", values, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitNotIn(List<Integer> values) {
            addCriterion("call_limit not in", values, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitBetween(Integer value1, Integer value2) {
            addCriterion("call_limit between", value1, value2, "callLimit");
            return (Criteria) this;
        }

        public Criteria andCallLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("call_limit not between", value1, value2, "callLimit");
            return (Criteria) this;
        }

        public Criteria andNeedLoginIsNull() {
            addCriterion("need_login is null");
            return (Criteria) this;
        }

        public Criteria andNeedLoginIsNotNull() {
            addCriterion("need_login is not null");
            return (Criteria) this;
        }

        public Criteria andNeedLoginEqualTo(Integer value) {
            addCriterion("need_login =", value, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginNotEqualTo(Integer value) {
            addCriterion("need_login <>", value, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginGreaterThan(Integer value) {
            addCriterion("need_login >", value, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_login >=", value, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginLessThan(Integer value) {
            addCriterion("need_login <", value, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginLessThanOrEqualTo(Integer value) {
            addCriterion("need_login <=", value, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginIn(List<Integer> values) {
            addCriterion("need_login in", values, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginNotIn(List<Integer> values) {
            addCriterion("need_login not in", values, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginBetween(Integer value1, Integer value2) {
            addCriterion("need_login between", value1, value2, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedLoginNotBetween(Integer value1, Integer value2) {
            addCriterion("need_login not between", value1, value2, "needLogin");
            return (Criteria) this;
        }

        public Criteria andNeedAuthIsNull() {
            addCriterion("need_auth is null");
            return (Criteria) this;
        }

        public Criteria andNeedAuthIsNotNull() {
            addCriterion("need_auth is not null");
            return (Criteria) this;
        }

        public Criteria andNeedAuthEqualTo(Integer value) {
            addCriterion("need_auth =", value, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthNotEqualTo(Integer value) {
            addCriterion("need_auth <>", value, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthGreaterThan(Integer value) {
            addCriterion("need_auth >", value, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_auth >=", value, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthLessThan(Integer value) {
            addCriterion("need_auth <", value, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthLessThanOrEqualTo(Integer value) {
            addCriterion("need_auth <=", value, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthIn(List<Integer> values) {
            addCriterion("need_auth in", values, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthNotIn(List<Integer> values) {
            addCriterion("need_auth not in", values, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthBetween(Integer value1, Integer value2) {
            addCriterion("need_auth between", value1, value2, "needAuth");
            return (Criteria) this;
        }

        public Criteria andNeedAuthNotBetween(Integer value1, Integer value2) {
            addCriterion("need_auth not between", value1, value2, "needAuth");
            return (Criteria) this;
        }

        public Criteria andHttpMethodIsNull() {
            addCriterion("http_method is null");
            return (Criteria) this;
        }

        public Criteria andHttpMethodIsNotNull() {
            addCriterion("http_method is not null");
            return (Criteria) this;
        }

        public Criteria andHttpMethodEqualTo(String value) {
            addCriterion("http_method =", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotEqualTo(String value) {
            addCriterion("http_method <>", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodGreaterThan(String value) {
            addCriterion("http_method >", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodGreaterThanOrEqualTo(String value) {
            addCriterion("http_method >=", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodLessThan(String value) {
            addCriterion("http_method <", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodLessThanOrEqualTo(String value) {
            addCriterion("http_method <=", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodLike(String value) {
            addCriterion("http_method like", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotLike(String value) {
            addCriterion("http_method not like", value, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodIn(List<String> values) {
            addCriterion("http_method in", values, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotIn(List<String> values) {
            addCriterion("http_method not in", values, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodBetween(String value1, String value2) {
            addCriterion("http_method between", value1, value2, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andHttpMethodNotBetween(String value1, String value2) {
            addCriterion("http_method not between", value1, value2, "httpMethod");
            return (Criteria) this;
        }

        public Criteria andApiTypeIsNull() {
            addCriterion("api_type is null");
            return (Criteria) this;
        }

        public Criteria andApiTypeIsNotNull() {
            addCriterion("api_type is not null");
            return (Criteria) this;
        }

        public Criteria andApiTypeEqualTo(Integer value) {
            addCriterion("api_type =", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeNotEqualTo(Integer value) {
            addCriterion("api_type <>", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeGreaterThan(Integer value) {
            addCriterion("api_type >", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("api_type >=", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeLessThan(Integer value) {
            addCriterion("api_type <", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeLessThanOrEqualTo(Integer value) {
            addCriterion("api_type <=", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeIn(List<Integer> values) {
            addCriterion("api_type in", values, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeNotIn(List<Integer> values) {
            addCriterion("api_type not in", values, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeBetween(Integer value1, Integer value2) {
            addCriterion("api_type between", value1, value2, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("api_type not between", value1, value2, "apiType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}