package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class ApiParamCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.api_id
     *
     * @mbggenerated
     */
    private Integer apiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.param_index
     *
     * @mbggenerated
     */
    private Integer paramIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.param_name
     *
     * @mbggenerated
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.param_desc
     *
     * @mbggenerated
     */
    private String paramDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.param_type
     *
     * @mbggenerated
     */
    private String paramType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.param_type_id
     *
     * @mbggenerated
     */
    private Integer paramTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.example
     *
     * @mbggenerated
     */
    private String example;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.is_required
     *
     * @mbggenerated
     */
    private Integer isRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param.param_source
     *
     * @mbggenerated
     */
    private Integer paramSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.id
     *
     * @return the value of api_param.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.id
     *
     * @param id the value for api_param.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.create_time
     *
     * @return the value of api_param.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.create_time
     *
     * @param createTime the value for api_param.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.update_time
     *
     * @return the value of api_param.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.update_time
     *
     * @param updateTime the value for api_param.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.deleted
     *
     * @return the value of api_param.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.deleted
     *
     * @param deleted the value for api_param.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.creator
     *
     * @return the value of api_param.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.creator
     *
     * @param creator the value for api_param.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.updater
     *
     * @return the value of api_param.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.updater
     *
     * @param updater the value for api_param.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.api_id
     *
     * @return the value of api_param.api_id
     *
     * @mbggenerated
     */
    public Integer getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.api_id
     *
     * @param apiId the value for api_param.api_id
     *
     * @mbggenerated
     */
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.param_index
     *
     * @return the value of api_param.param_index
     *
     * @mbggenerated
     */
    public Integer getParamIndex() {
        return paramIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.param_index
     *
     * @param paramIndex the value for api_param.param_index
     *
     * @mbggenerated
     */
    public void setParamIndex(Integer paramIndex) {
        this.paramIndex = paramIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.param_name
     *
     * @return the value of api_param.param_name
     *
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.param_name
     *
     * @param paramName the value for api_param.param_name
     *
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.param_desc
     *
     * @return the value of api_param.param_desc
     *
     * @mbggenerated
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.param_desc
     *
     * @param paramDesc the value for api_param.param_desc
     *
     * @mbggenerated
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc == null ? null : paramDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.param_type
     *
     * @return the value of api_param.param_type
     *
     * @mbggenerated
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.param_type
     *
     * @param paramType the value for api_param.param_type
     *
     * @mbggenerated
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.param_type_id
     *
     * @return the value of api_param.param_type_id
     *
     * @mbggenerated
     */
    public Integer getParamTypeId() {
        return paramTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.param_type_id
     *
     * @param paramTypeId the value for api_param.param_type_id
     *
     * @mbggenerated
     */
    public void setParamTypeId(Integer paramTypeId) {
        this.paramTypeId = paramTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.example
     *
     * @return the value of api_param.example
     *
     * @mbggenerated
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.example
     *
     * @param example the value for api_param.example
     *
     * @mbggenerated
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.is_required
     *
     * @return the value of api_param.is_required
     *
     * @mbggenerated
     */
    public Integer getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.is_required
     *
     * @param isRequired the value for api_param.is_required
     *
     * @mbggenerated
     */
    public void setIsRequired(Integer isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param.param_source
     *
     * @return the value of api_param.param_source
     *
     * @mbggenerated
     */
    public Integer getParamSource() {
        return paramSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param.param_source
     *
     * @param paramSource the value for api_param.param_source
     *
     * @mbggenerated
     */
    public void setParamSource(Integer paramSource) {
        this.paramSource = paramSource;
    }
}