package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class ApiResultCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.api_id
     *
     * @mbggenerated
     */
    private Integer apiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.field_index
     *
     * @mbggenerated
     */
    private Integer fieldIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.field_desc
     *
     * @mbggenerated
     */
    private String fieldDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.field_name
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.back_field_name
     *
     * @mbggenerated
     */
    private String backFieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.field_type
     *
     * @mbggenerated
     */
    private String fieldType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_result.example
     *
     * @mbggenerated
     */
    private String example;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.id
     *
     * @return the value of api_result.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.id
     *
     * @param id the value for api_result.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.create_time
     *
     * @return the value of api_result.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.create_time
     *
     * @param createTime the value for api_result.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.update_time
     *
     * @return the value of api_result.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.update_time
     *
     * @param updateTime the value for api_result.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.deleted
     *
     * @return the value of api_result.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.deleted
     *
     * @param deleted the value for api_result.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.creator
     *
     * @return the value of api_result.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.creator
     *
     * @param creator the value for api_result.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.updater
     *
     * @return the value of api_result.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.updater
     *
     * @param updater the value for api_result.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.api_id
     *
     * @return the value of api_result.api_id
     *
     * @mbggenerated
     */
    public Integer getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.api_id
     *
     * @param apiId the value for api_result.api_id
     *
     * @mbggenerated
     */
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.field_index
     *
     * @return the value of api_result.field_index
     *
     * @mbggenerated
     */
    public Integer getFieldIndex() {
        return fieldIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.field_index
     *
     * @param fieldIndex the value for api_result.field_index
     *
     * @mbggenerated
     */
    public void setFieldIndex(Integer fieldIndex) {
        this.fieldIndex = fieldIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.field_desc
     *
     * @return the value of api_result.field_desc
     *
     * @mbggenerated
     */
    public String getFieldDesc() {
        return fieldDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.field_desc
     *
     * @param fieldDesc the value for api_result.field_desc
     *
     * @mbggenerated
     */
    public void setFieldDesc(String fieldDesc) {
        this.fieldDesc = fieldDesc == null ? null : fieldDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.field_name
     *
     * @return the value of api_result.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.field_name
     *
     * @param fieldName the value for api_result.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.back_field_name
     *
     * @return the value of api_result.back_field_name
     *
     * @mbggenerated
     */
    public String getBackFieldName() {
        return backFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.back_field_name
     *
     * @param backFieldName the value for api_result.back_field_name
     *
     * @mbggenerated
     */
    public void setBackFieldName(String backFieldName) {
        this.backFieldName = backFieldName == null ? null : backFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.field_type
     *
     * @return the value of api_result.field_type
     *
     * @mbggenerated
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.field_type
     *
     * @param fieldType the value for api_result.field_type
     *
     * @mbggenerated
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType == null ? null : fieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_result.example
     *
     * @return the value of api_result.example
     *
     * @mbggenerated
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_result.example
     *
     * @param example the value for api_result.example
     *
     * @mbggenerated
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }
}