package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class Auth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.api_group
     *
     * @mbggenerated
     */
    private Integer apiGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.id
     *
     * @return the value of auth.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.id
     *
     * @param id the value for auth.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.create_time
     *
     * @return the value of auth.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.create_time
     *
     * @param createTime the value for auth.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.user_id
     *
     * @return the value of auth.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.user_id
     *
     * @param userId the value for auth.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.api_group
     *
     * @return the value of auth.api_group
     *
     * @mbggenerated
     */
    public Integer getApiGroup() {
        return apiGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.api_group
     *
     * @param apiGroup the value for auth.api_group
     *
     * @mbggenerated
     */
    public void setApiGroup(Integer apiGroup) {
        this.apiGroup = apiGroup;
    }
}