package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class PojoType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.type_ename
     *
     * @mbggenerated
     */
    private String typeEname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.type_cname
     *
     * @mbggenerated
     */
    private String typeCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type.type_class
     *
     * @mbggenerated
     */
    private String typeClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.id
     *
     * @return the value of pojo_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.id
     *
     * @param id the value for pojo_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.create_time
     *
     * @return the value of pojo_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.create_time
     *
     * @param createTime the value for pojo_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.update_time
     *
     * @return the value of pojo_type.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.update_time
     *
     * @param updateTime the value for pojo_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.deleted
     *
     * @return the value of pojo_type.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.deleted
     *
     * @param deleted the value for pojo_type.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.state
     *
     * @return the value of pojo_type.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.state
     *
     * @param state the value for pojo_type.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.creator
     *
     * @return the value of pojo_type.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.creator
     *
     * @param creator the value for pojo_type.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.updater
     *
     * @return the value of pojo_type.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.updater
     *
     * @param updater the value for pojo_type.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.type_ename
     *
     * @return the value of pojo_type.type_ename
     *
     * @mbggenerated
     */
    public String getTypeEname() {
        return typeEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.type_ename
     *
     * @param typeEname the value for pojo_type.type_ename
     *
     * @mbggenerated
     */
    public void setTypeEname(String typeEname) {
        this.typeEname = typeEname == null ? null : typeEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.type_cname
     *
     * @return the value of pojo_type.type_cname
     *
     * @mbggenerated
     */
    public String getTypeCname() {
        return typeCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.type_cname
     *
     * @param typeCname the value for pojo_type.type_cname
     *
     * @mbggenerated
     */
    public void setTypeCname(String typeCname) {
        this.typeCname = typeCname == null ? null : typeCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type.type_class
     *
     * @return the value of pojo_type.type_class
     *
     * @mbggenerated
     */
    public String getTypeClass() {
        return typeClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type.type_class
     *
     * @param typeClass the value for pojo_type.type_class
     *
     * @mbggenerated
     */
    public void setTypeClass(String typeClass) {
        this.typeClass = typeClass == null ? null : typeClass.trim();
    }
}