package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class PojoStruct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.struct_ref
     *
     * @mbggenerated
     */
    private String structRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_struct.struct_type
     *
     * @mbggenerated
     */
    private Integer structType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.id
     *
     * @return the value of pojo_struct.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.id
     *
     * @param id the value for pojo_struct.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.create_time
     *
     * @return the value of pojo_struct.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.create_time
     *
     * @param createTime the value for pojo_struct.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.update_time
     *
     * @return the value of pojo_struct.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.update_time
     *
     * @param updateTime the value for pojo_struct.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.deleted
     *
     * @return the value of pojo_struct.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.deleted
     *
     * @param deleted the value for pojo_struct.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.state
     *
     * @return the value of pojo_struct.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.state
     *
     * @param state the value for pojo_struct.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.creator
     *
     * @return the value of pojo_struct.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.creator
     *
     * @param creator the value for pojo_struct.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.updater
     *
     * @return the value of pojo_struct.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.updater
     *
     * @param updater the value for pojo_struct.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.type_id
     *
     * @return the value of pojo_struct.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.type_id
     *
     * @param typeId the value for pojo_struct.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.name
     *
     * @return the value of pojo_struct.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.name
     *
     * @param name the value for pojo_struct.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.struct_ref
     *
     * @return the value of pojo_struct.struct_ref
     *
     * @mbggenerated
     */
    public String getStructRef() {
        return structRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.struct_ref
     *
     * @param structRef the value for pojo_struct.struct_ref
     *
     * @mbggenerated
     */
    public void setStructRef(String structRef) {
        this.structRef = structRef == null ? null : structRef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_struct.struct_type
     *
     * @return the value of pojo_struct.struct_type
     *
     * @mbggenerated
     */
    public Integer getStructType() {
        return structType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_struct.struct_type
     *
     * @param structType the value for pojo_struct.struct_type
     *
     * @mbggenerated
     */
    public void setStructType(Integer structType) {
        this.structType = structType;
    }
}