package com.zhiyong.gateway.dal.domain;

import java.util.Date;

public class PojoTypeJson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.is_pojo
     *
     * @mbggenerated
     */
    private Integer isPojo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.type_desc
     *
     * @mbggenerated
     */
    private String typeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pojo_type_json.type_json
     *
     * @mbggenerated
     */
    private String typeJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.id
     *
     * @return the value of pojo_type_json.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.id
     *
     * @param id the value for pojo_type_json.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.create_time
     *
     * @return the value of pojo_type_json.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.create_time
     *
     * @param createTime the value for pojo_type_json.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.update_time
     *
     * @return the value of pojo_type_json.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.update_time
     *
     * @param updateTime the value for pojo_type_json.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.deleted
     *
     * @return the value of pojo_type_json.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.deleted
     *
     * @param deleted the value for pojo_type_json.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.state
     *
     * @return the value of pojo_type_json.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.state
     *
     * @param state the value for pojo_type_json.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.creator
     *
     * @return the value of pojo_type_json.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.creator
     *
     * @param creator the value for pojo_type_json.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.updater
     *
     * @return the value of pojo_type_json.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.updater
     *
     * @param updater the value for pojo_type_json.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.is_pojo
     *
     * @return the value of pojo_type_json.is_pojo
     *
     * @mbggenerated
     */
    public Integer getIsPojo() {
        return isPojo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.is_pojo
     *
     * @param isPojo the value for pojo_type_json.is_pojo
     *
     * @mbggenerated
     */
    public void setIsPojo(Integer isPojo) {
        this.isPojo = isPojo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.type_name
     *
     * @return the value of pojo_type_json.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.type_name
     *
     * @param typeName the value for pojo_type_json.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.type_desc
     *
     * @return the value of pojo_type_json.type_desc
     *
     * @mbggenerated
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.type_desc
     *
     * @param typeDesc the value for pojo_type_json.type_desc
     *
     * @mbggenerated
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc == null ? null : typeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pojo_type_json.type_json
     *
     * @return the value of pojo_type_json.type_json
     *
     * @mbggenerated
     */
    public String getTypeJson() {
        return typeJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pojo_type_json.type_json
     *
     * @param typeJson the value for pojo_type_json.type_json
     *
     * @mbggenerated
     */
    public void setTypeJson(String typeJson) {
        this.typeJson = typeJson == null ? null : typeJson.trim();
    }
}